## -------------------------------------------------------
## File: techapplistwrite.R
##
## December, 2017 ??? Dorothee Spuhler
## dorothee.spuhler@eawag.ch
##
##   This program is free software: you can redistribute it and/or modify
##   it under the terms of the GNU General Public License as published by
##   the Free Software Foundation, either version 3 of the License, or
##   (at your option) any later version.
##
##   This program is distributed in the hope that it will be useful,
##   but WITHOUT ANY WARRANTY; without even the implied warranty of
##   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##   GNU General Public License for more details.
##
##   You should have received a copy of the GNU General Public License
##   along with this program.  If not, see <http://www.gnu.org/licenses/>.
##
## ==============================================================================================

techapplist.write=function(techapplist, listsep=" ", filename=""){
  # Description
  # Write techapplist to the screen or file
  # Usage
  # techapplist.write(techapplist,listsep=" ",filename="")
  # Input:
  # techapplist: list of appropriatness technologies as generated by app.compute.R 
  # listsep: separato, default=" "
  # filename: output file, if empty string (""), write to standard output, default=""
  
  # auxiliar values
  profilesep=", " #separator for techapp.profile
  ndigit=5     #number of digits
  
  #Set output mode
  if (filename!="") sink(file=filename, append=FALSE) #redirect cat to file
  
  #Write header
  header=paste("case        ", listsep, "tech             ",listsep, "techapp.score", listsep, "techapp.profile","\n")
  cat(header)
  
  
  #Loop over all element
  for (id in 1:length(techapplist)){
    elem=techapplist[[id]]  #list element
    
    #prepare profile list
    profile=elem$techapp.profile
    profilestr=""     #string to write techapp.profile
    for (pid in 1:length(profile)){
      if (pid==1){
        profilestr=paste(names(profile[pid]),"=",format(profile[pid],digits=ndigit)) #no separtor for first element
      }else{
        profilestr=paste(profilestr,profilesep,names(profile[pid]),"=",format(profile[pid],digits=ndigit))
      }
    }
    
    #Combine print
    lineout=paste(format(elem$case,width=12),
                  listsep,format(elem$tech,width=20),
                  listsep,format(elem$techapp.score,digits=ndigit,width=10),
                  listsep,profilestr,"\n")
    cat(lineout)
  }
  if (filename!="") sink(file=NULL) #stop redirection
}
